package sitetech.NFCcheckPoint.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "EMPRESA".
 */
@Entity
public class Empresa {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String nombre;
    private String telefono;
    private boolean eliminado;
    private String extraString;
    private Integer extraInt;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Empresa() {
    }

    public Empresa(Long id) {
        this.id = id;
    }

    @Generated
    public Empresa(Long id, String nombre, String telefono, boolean eliminado, String extraString, Integer extraInt) {
        this.id = id;
        this.nombre = nombre;
        this.telefono = telefono;
        this.eliminado = eliminado;
        this.extraString = extraString;
        this.extraInt = extraInt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getNombre() {
        return nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(@NotNull String nombre) {
        this.nombre = nombre;
    }

    public String getTelefono() {
        return telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public boolean getEliminado() {
        return eliminado;
    }

    public void setEliminado(boolean eliminado) {
        this.eliminado = eliminado;
    }

    public String getExtraString() {
        return extraString;
    }

    public void setExtraString(String extraString) {
        this.extraString = extraString;
    }

    public Integer getExtraInt() {
        return extraInt;
    }

    public void setExtraInt(Integer extraInt) {
        this.extraInt = extraInt;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
