package sitetech.NFCcheckPoint.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "HORARIO".
 */
@Entity
public class Horario {

    @Id(autoincrement = true)
    private Long id;
    private String nombre;
    private String hora;
    private Integer maxMinutos;
    private String horaFestivo;
    private Integer maxMinutosFestivo;
    private String horaFinSemana;
    private Integer maxMinutosFinSemana;
    private boolean eliminado;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Horario() {
    }

    public Horario(Long id) {
        this.id = id;
    }

    @Generated
    public Horario(Long id, String nombre, String hora, Integer maxMinutos, String horaFestivo, Integer maxMinutosFestivo, String horaFinSemana, Integer maxMinutosFinSemana, boolean eliminado) {
        this.id = id;
        this.nombre = nombre;
        this.hora = hora;
        this.maxMinutos = maxMinutos;
        this.horaFestivo = horaFestivo;
        this.maxMinutosFestivo = maxMinutosFestivo;
        this.horaFinSemana = horaFinSemana;
        this.maxMinutosFinSemana = maxMinutosFinSemana;
        this.eliminado = eliminado;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getHora() {
        return hora;
    }

    public void setHora(String hora) {
        this.hora = hora;
    }

    public Integer getMaxMinutos() {
        return maxMinutos;
    }

    public void setMaxMinutos(Integer maxMinutos) {
        this.maxMinutos = maxMinutos;
    }

    public String getHoraFestivo() {
        return horaFestivo;
    }

    public void setHoraFestivo(String horaFestivo) {
        this.horaFestivo = horaFestivo;
    }

    public Integer getMaxMinutosFestivo() {
        return maxMinutosFestivo;
    }

    public void setMaxMinutosFestivo(Integer maxMinutosFestivo) {
        this.maxMinutosFestivo = maxMinutosFestivo;
    }

    public String getHoraFinSemana() {
        return horaFinSemana;
    }

    public void setHoraFinSemana(String horaFinSemana) {
        this.horaFinSemana = horaFinSemana;
    }

    public Integer getMaxMinutosFinSemana() {
        return maxMinutosFinSemana;
    }

    public void setMaxMinutosFinSemana(Integer maxMinutosFinSemana) {
        this.maxMinutosFinSemana = maxMinutosFinSemana;
    }

    public boolean getEliminado() {
        return eliminado;
    }

    public void setEliminado(boolean eliminado) {
        this.eliminado = eliminado;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
