package sitetech.NFCcheckPoint.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HORARIO".
*/
public class HorarioDao extends AbstractDao<Horario, Long> {

    public static final String TABLENAME = "HORARIO";

    /**
     * Properties of entity Horario.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Hora = new Property(1, java.util.Date.class, "hora", false, "HORA");
        public final static Property MaxMinutos = new Property(2, Integer.class, "maxMinutos", false, "MAX_MINUTOS");
        public final static Property HoraFestivo = new Property(3, java.util.Date.class, "horaFestivo", false, "HORA_FESTIVO");
        public final static Property MaxMinutosFestivo = new Property(4, Integer.class, "maxMinutosFestivo", false, "MAX_MINUTOS_FESTIVO");
        public final static Property HoraFinSemana = new Property(5, java.util.Date.class, "horaFinSemana", false, "HORA_FIN_SEMANA");
        public final static Property MaxMinutosFinSemana = new Property(6, Integer.class, "maxMinutosFinSemana", false, "MAX_MINUTOS_FIN_SEMANA");
        public final static Property Eliminado = new Property(7, boolean.class, "eliminado", false, "ELIMINADO");
    }


    public HorarioDao(DaoConfig config) {
        super(config);
    }
    
    public HorarioDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HORARIO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"HORA\" INTEGER," + // 1: hora
                "\"MAX_MINUTOS\" INTEGER," + // 2: maxMinutos
                "\"HORA_FESTIVO\" INTEGER," + // 3: horaFestivo
                "\"MAX_MINUTOS_FESTIVO\" INTEGER," + // 4: maxMinutosFestivo
                "\"HORA_FIN_SEMANA\" INTEGER," + // 5: horaFinSemana
                "\"MAX_MINUTOS_FIN_SEMANA\" INTEGER," + // 6: maxMinutosFinSemana
                "\"ELIMINADO\" INTEGER NOT NULL );"); // 7: eliminado
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HORARIO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Horario entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        java.util.Date hora = entity.getHora();
        if (hora != null) {
            stmt.bindLong(2, hora.getTime());
        }
 
        Integer maxMinutos = entity.getMaxMinutos();
        if (maxMinutos != null) {
            stmt.bindLong(3, maxMinutos);
        }
 
        java.util.Date horaFestivo = entity.getHoraFestivo();
        if (horaFestivo != null) {
            stmt.bindLong(4, horaFestivo.getTime());
        }
 
        Integer maxMinutosFestivo = entity.getMaxMinutosFestivo();
        if (maxMinutosFestivo != null) {
            stmt.bindLong(5, maxMinutosFestivo);
        }
 
        java.util.Date horaFinSemana = entity.getHoraFinSemana();
        if (horaFinSemana != null) {
            stmt.bindLong(6, horaFinSemana.getTime());
        }
 
        Integer maxMinutosFinSemana = entity.getMaxMinutosFinSemana();
        if (maxMinutosFinSemana != null) {
            stmt.bindLong(7, maxMinutosFinSemana);
        }
        stmt.bindLong(8, entity.getEliminado() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Horario entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        java.util.Date hora = entity.getHora();
        if (hora != null) {
            stmt.bindLong(2, hora.getTime());
        }
 
        Integer maxMinutos = entity.getMaxMinutos();
        if (maxMinutos != null) {
            stmt.bindLong(3, maxMinutos);
        }
 
        java.util.Date horaFestivo = entity.getHoraFestivo();
        if (horaFestivo != null) {
            stmt.bindLong(4, horaFestivo.getTime());
        }
 
        Integer maxMinutosFestivo = entity.getMaxMinutosFestivo();
        if (maxMinutosFestivo != null) {
            stmt.bindLong(5, maxMinutosFestivo);
        }
 
        java.util.Date horaFinSemana = entity.getHoraFinSemana();
        if (horaFinSemana != null) {
            stmt.bindLong(6, horaFinSemana.getTime());
        }
 
        Integer maxMinutosFinSemana = entity.getMaxMinutosFinSemana();
        if (maxMinutosFinSemana != null) {
            stmt.bindLong(7, maxMinutosFinSemana);
        }
        stmt.bindLong(8, entity.getEliminado() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Horario readEntity(Cursor cursor, int offset) {
        Horario entity = new Horario( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // hora
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // maxMinutos
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // horaFestivo
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // maxMinutosFestivo
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // horaFinSemana
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // maxMinutosFinSemana
            cursor.getShort(offset + 7) != 0 // eliminado
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Horario entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHora(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setMaxMinutos(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setHoraFestivo(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setMaxMinutosFestivo(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setHoraFinSemana(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setMaxMinutosFinSemana(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setEliminado(cursor.getShort(offset + 7) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Horario entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Horario entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Horario entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
