package sitetech.NFCcheckPoint.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HORARIO_POR_RUTA".
*/
public class horarioPorRutaDao extends AbstractDao<horarioPorRuta, Long> {

    public static final String TABLENAME = "HORARIO_POR_RUTA";

    /**
     * Properties of entity horarioPorRuta.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RutaId = new Property(1, long.class, "rutaId", false, "RUTA_ID");
        public final static Property HorarioId = new Property(2, long.class, "horarioId", false, "HORARIO_ID");
        public final static Property Eliminado = new Property(3, boolean.class, "eliminado", false, "ELIMINADO");
    }

    private DaoSession daoSession;


    public horarioPorRutaDao(DaoConfig config) {
        super(config);
    }
    
    public horarioPorRutaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HORARIO_POR_RUTA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"RUTA_ID\" INTEGER NOT NULL ," + // 1: rutaId
                "\"HORARIO_ID\" INTEGER NOT NULL ," + // 2: horarioId
                "\"ELIMINADO\" INTEGER NOT NULL );"); // 3: eliminado
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HORARIO_POR_RUTA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, horarioPorRuta entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getRutaId());
        stmt.bindLong(3, entity.getHorarioId());
        stmt.bindLong(4, entity.getEliminado() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, horarioPorRuta entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getRutaId());
        stmt.bindLong(3, entity.getHorarioId());
        stmt.bindLong(4, entity.getEliminado() ? 1L: 0L);
    }

    @Override
    protected final void attachEntity(horarioPorRuta entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public horarioPorRuta readEntity(Cursor cursor, int offset) {
        horarioPorRuta entity = new horarioPorRuta( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // rutaId
            cursor.getLong(offset + 2), // horarioId
            cursor.getShort(offset + 3) != 0 // eliminado
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, horarioPorRuta entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRutaId(cursor.getLong(offset + 1));
        entity.setHorarioId(cursor.getLong(offset + 2));
        entity.setEliminado(cursor.getShort(offset + 3) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(horarioPorRuta entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(horarioPorRuta entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(horarioPorRuta entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getHorarioDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getRutaDao().getAllColumns());
            builder.append(" FROM HORARIO_POR_RUTA T");
            builder.append(" LEFT JOIN HORARIO T0 ON T.\"HORARIO_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN RUTA T1 ON T.\"RUTA_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected horarioPorRuta loadCurrentDeep(Cursor cursor, boolean lock) {
        horarioPorRuta entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Horario horario = loadCurrentOther(daoSession.getHorarioDao(), cursor, offset);
         if(horario != null) {
            entity.setHorario(horario);
        }
        offset += daoSession.getHorarioDao().getAllColumns().length;

        Ruta ruta = loadCurrentOther(daoSession.getRutaDao(), cursor, offset);
         if(ruta != null) {
            entity.setRuta(ruta);
        }

        return entity;    
    }

    public horarioPorRuta loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<horarioPorRuta> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<horarioPorRuta> list = new ArrayList<horarioPorRuta>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<horarioPorRuta> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<horarioPorRuta> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
