package sitetech.NFCcheckPoint.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "HORARIO".
 */
@Entity
public class Horario {

    @Id(autoincrement = true)
    private Long id;
    private String nombre;
    private String horaDesde;
    private String horaHasta;
    private Integer maxMinutos;
    private String tiempoNormal;
    private String horaFestivoDesde;
    private String horaFestivoHasta;
    private String tiempoDiaFestivo;
    private Integer maxMinutosFestivo;
    private String horaFinSemanaDesde;
    private String horaFinSemanaHasta;
    private String tiempoFinSemana;
    private Integer maxMinutosFinSemana;
    private boolean eliminado;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Horario() {
    }

    public Horario(Long id) {
        this.id = id;
    }

    @Generated
    public Horario(Long id, String nombre, String horaDesde, String horaHasta, Integer maxMinutos, String tiempoNormal, String horaFestivoDesde, String horaFestivoHasta, String tiempoDiaFestivo, Integer maxMinutosFestivo, String horaFinSemanaDesde, String horaFinSemanaHasta, String tiempoFinSemana, Integer maxMinutosFinSemana, boolean eliminado) {
        this.id = id;
        this.nombre = nombre;
        this.horaDesde = horaDesde;
        this.horaHasta = horaHasta;
        this.maxMinutos = maxMinutos;
        this.tiempoNormal = tiempoNormal;
        this.horaFestivoDesde = horaFestivoDesde;
        this.horaFestivoHasta = horaFestivoHasta;
        this.tiempoDiaFestivo = tiempoDiaFestivo;
        this.maxMinutosFestivo = maxMinutosFestivo;
        this.horaFinSemanaDesde = horaFinSemanaDesde;
        this.horaFinSemanaHasta = horaFinSemanaHasta;
        this.tiempoFinSemana = tiempoFinSemana;
        this.maxMinutosFinSemana = maxMinutosFinSemana;
        this.eliminado = eliminado;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getHoraDesde() {
        return horaDesde;
    }

    public void setHoraDesde(String horaDesde) {
        this.horaDesde = horaDesde;
    }

    public String getHoraHasta() {
        return horaHasta;
    }

    public void setHoraHasta(String horaHasta) {
        this.horaHasta = horaHasta;
    }

    public Integer getMaxMinutos() {
        return maxMinutos;
    }

    public void setMaxMinutos(Integer maxMinutos) {
        this.maxMinutos = maxMinutos;
    }

    public String getTiempoNormal() {
        return tiempoNormal;
    }

    public void setTiempoNormal(String tiempoNormal) {
        this.tiempoNormal = tiempoNormal;
    }

    public String getHoraFestivoDesde() {
        return horaFestivoDesde;
    }

    public void setHoraFestivoDesde(String horaFestivoDesde) {
        this.horaFestivoDesde = horaFestivoDesde;
    }

    public String getHoraFestivoHasta() {
        return horaFestivoHasta;
    }

    public void setHoraFestivoHasta(String horaFestivoHasta) {
        this.horaFestivoHasta = horaFestivoHasta;
    }

    public String getTiempoDiaFestivo() {
        return tiempoDiaFestivo;
    }

    public void setTiempoDiaFestivo(String tiempoDiaFestivo) {
        this.tiempoDiaFestivo = tiempoDiaFestivo;
    }

    public Integer getMaxMinutosFestivo() {
        return maxMinutosFestivo;
    }

    public void setMaxMinutosFestivo(Integer maxMinutosFestivo) {
        this.maxMinutosFestivo = maxMinutosFestivo;
    }

    public String getHoraFinSemanaDesde() {
        return horaFinSemanaDesde;
    }

    public void setHoraFinSemanaDesde(String horaFinSemanaDesde) {
        this.horaFinSemanaDesde = horaFinSemanaDesde;
    }

    public String getHoraFinSemanaHasta() {
        return horaFinSemanaHasta;
    }

    public void setHoraFinSemanaHasta(String horaFinSemanaHasta) {
        this.horaFinSemanaHasta = horaFinSemanaHasta;
    }

    public String getTiempoFinSemana() {
        return tiempoFinSemana;
    }

    public void setTiempoFinSemana(String tiempoFinSemana) {
        this.tiempoFinSemana = tiempoFinSemana;
    }

    public Integer getMaxMinutosFinSemana() {
        return maxMinutosFinSemana;
    }

    public void setMaxMinutosFinSemana(Integer maxMinutosFinSemana) {
        this.maxMinutosFinSemana = maxMinutosFinSemana;
    }

    public boolean getEliminado() {
        return eliminado;
    }

    public void setEliminado(boolean eliminado) {
        this.eliminado = eliminado;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
