package sitetech.NFCcheckPoint.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "HORARIO".
 */
@Entity
public class Horario {

    @Id(autoincrement = true)
    private Long id;
    private java.util.Date hora;
    private Integer maxMinutos;
    private java.util.Date horaFestivo;
    private Integer maxMinutosFestivo;
    private java.util.Date horaFinSemana;
    private Integer maxMinutosFinSemana;
    private boolean eliminado;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Horario() {
    }

    public Horario(Long id) {
        this.id = id;
    }

    @Generated
    public Horario(Long id, java.util.Date hora, Integer maxMinutos, java.util.Date horaFestivo, Integer maxMinutosFestivo, java.util.Date horaFinSemana, Integer maxMinutosFinSemana, boolean eliminado) {
        this.id = id;
        this.hora = hora;
        this.maxMinutos = maxMinutos;
        this.horaFestivo = horaFestivo;
        this.maxMinutosFestivo = maxMinutosFestivo;
        this.horaFinSemana = horaFinSemana;
        this.maxMinutosFinSemana = maxMinutosFinSemana;
        this.eliminado = eliminado;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getHora() {
        return hora;
    }

    public void setHora(java.util.Date hora) {
        this.hora = hora;
    }

    public Integer getMaxMinutos() {
        return maxMinutos;
    }

    public void setMaxMinutos(Integer maxMinutos) {
        this.maxMinutos = maxMinutos;
    }

    public java.util.Date getHoraFestivo() {
        return horaFestivo;
    }

    public void setHoraFestivo(java.util.Date horaFestivo) {
        this.horaFestivo = horaFestivo;
    }

    public Integer getMaxMinutosFestivo() {
        return maxMinutosFestivo;
    }

    public void setMaxMinutosFestivo(Integer maxMinutosFestivo) {
        this.maxMinutosFestivo = maxMinutosFestivo;
    }

    public java.util.Date getHoraFinSemana() {
        return horaFinSemana;
    }

    public void setHoraFinSemana(java.util.Date horaFinSemana) {
        this.horaFinSemana = horaFinSemana;
    }

    public Integer getMaxMinutosFinSemana() {
        return maxMinutosFinSemana;
    }

    public void setMaxMinutosFinSemana(Integer maxMinutosFinSemana) {
        this.maxMinutosFinSemana = maxMinutosFinSemana;
    }

    public boolean getEliminado() {
        return eliminado;
    }

    public void setEliminado(boolean eliminado) {
        this.eliminado = eliminado;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
