package sitetech.NFCcheckPoint.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PUNTO".
 */
@Entity
public class Punto {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String nombre;
    private boolean eliminada;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Punto() {
    }

    public Punto(Long id) {
        this.id = id;
    }

    @Generated
    public Punto(Long id, String nombre, boolean eliminada) {
        this.id = id;
        this.nombre = nombre;
        this.eliminada = eliminada;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getNombre() {
        return nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(@NotNull String nombre) {
        this.nombre = nombre;
    }

    public boolean getEliminada() {
        return eliminada;
    }

    public void setEliminada(boolean eliminada) {
        this.eliminada = eliminada;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
