package sitetech.NFCcheckPoint.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "REGISTRO_CAJA".
*/
public class registroCajaDao extends AbstractDao<registroCaja, Long> {

    public static final String TABLENAME = "REGISTRO_CAJA";

    /**
     * Properties of entity registroCaja.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Fecha = new Property(1, java.util.Date.class, "fecha", false, "FECHA");
        public final static Property Eliminado = new Property(2, Boolean.class, "eliminado", false, "ELIMINADO");
        public final static Property BusId = new Property(3, long.class, "busId", false, "BUS_ID");
        public final static Property RutaId = new Property(4, long.class, "rutaId", false, "RUTA_ID");
        public final static Property CajaId = new Property(5, long.class, "cajaId", false, "CAJA_ID");
    }

    private DaoSession daoSession;


    public registroCajaDao(DaoConfig config) {
        super(config);
    }
    
    public registroCajaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"REGISTRO_CAJA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"FECHA\" INTEGER," + // 1: fecha
                "\"ELIMINADO\" INTEGER," + // 2: eliminado
                "\"BUS_ID\" INTEGER NOT NULL ," + // 3: busId
                "\"RUTA_ID\" INTEGER NOT NULL ," + // 4: rutaId
                "\"CAJA_ID\" INTEGER NOT NULL );"); // 5: cajaId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"REGISTRO_CAJA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, registroCaja entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        java.util.Date fecha = entity.getFecha();
        if (fecha != null) {
            stmt.bindLong(2, fecha.getTime());
        }
 
        Boolean eliminado = entity.getEliminado();
        if (eliminado != null) {
            stmt.bindLong(3, eliminado ? 1L: 0L);
        }
        stmt.bindLong(4, entity.getBusId());
        stmt.bindLong(5, entity.getRutaId());
        stmt.bindLong(6, entity.getCajaId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, registroCaja entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        java.util.Date fecha = entity.getFecha();
        if (fecha != null) {
            stmt.bindLong(2, fecha.getTime());
        }
 
        Boolean eliminado = entity.getEliminado();
        if (eliminado != null) {
            stmt.bindLong(3, eliminado ? 1L: 0L);
        }
        stmt.bindLong(4, entity.getBusId());
        stmt.bindLong(5, entity.getRutaId());
        stmt.bindLong(6, entity.getCajaId());
    }

    @Override
    protected final void attachEntity(registroCaja entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public registroCaja readEntity(Cursor cursor, int offset) {
        registroCaja entity = new registroCaja( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // fecha
            cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0, // eliminado
            cursor.getLong(offset + 3), // busId
            cursor.getLong(offset + 4), // rutaId
            cursor.getLong(offset + 5) // cajaId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, registroCaja entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFecha(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setEliminado(cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0);
        entity.setBusId(cursor.getLong(offset + 3));
        entity.setRutaId(cursor.getLong(offset + 4));
        entity.setCajaId(cursor.getLong(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(registroCaja entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(registroCaja entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(registroCaja entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBusDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getRutaDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getCajaDao().getAllColumns());
            builder.append(" FROM REGISTRO_CAJA T");
            builder.append(" LEFT JOIN BUS T0 ON T.\"BUS_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN RUTA T1 ON T.\"RUTA_ID\"=T1.\"_id\"");
            builder.append(" LEFT JOIN CAJA T2 ON T.\"CAJA_ID\"=T2.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected registroCaja loadCurrentDeep(Cursor cursor, boolean lock) {
        registroCaja entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Bus bus = loadCurrentOther(daoSession.getBusDao(), cursor, offset);
         if(bus != null) {
            entity.setBus(bus);
        }
        offset += daoSession.getBusDao().getAllColumns().length;

        Ruta ruta = loadCurrentOther(daoSession.getRutaDao(), cursor, offset);
         if(ruta != null) {
            entity.setRuta(ruta);
        }
        offset += daoSession.getRutaDao().getAllColumns().length;

        Caja caja = loadCurrentOther(daoSession.getCajaDao(), cursor, offset);
         if(caja != null) {
            entity.setCaja(caja);
        }

        return entity;    
    }

    public registroCaja loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<registroCaja> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<registroCaja> list = new ArrayList<registroCaja>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<registroCaja> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<registroCaja> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
